name: FrictionLog
options:
  bundleIdPrefix: com.frictionlog
  deploymentTarget:
    macOS: "13.0"
  developmentLanguage: en

targets:
  FrictionLog:
    type: application
    platform: macOS
    sources:
      - path: FrictionLog/FrictionLog
        name: FrictionLog
        excludes:
          - "**/.DS_Store"
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.frictionlog.FrictionLog
      MARKETING_VERSION: "1.0"
      CURRENT_PROJECT_VERSION: "1"
      ENABLE_PREVIEWS: YES
      SWIFT_VERSION: "5.0"
      MACOSX_DEPLOYMENT_TARGET: "13.0"
      GENERATE_INFOPLIST_FILE: YES
      INFOPLIST_KEY_NSHumanReadableCopyright: ""
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      CODE_SIGN_STYLE: Automatic
      COMBINE_HIDPI_IMAGES: YES
      LD_RUNPATH_SEARCH_PATHS: "@executable_path/../Frameworks"
